@id = 46d12697-1624-4452-8362-38191e1fbdcf
PUT http://localhost:5089/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine",
    "description": "Scrambled Egg",
    "startDateTime": "2021-01-01T00:00:00",
    "endDateTime": "2021-01-01T00:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette"
    ],
    "sweet":[
        "Cookie"
    ]
}